#pragma once


#include "BDeV/BvCore.h"
#include "BDeV/Utils/BvUtils.h"
#include "BDeV/Utils/BvEnum.h"


// Kept the same as virtual key codes for simplicity
enum class BvKey : u8
{
	kNone				=	0  ,	// None
	kLButton			=	1  ,	// Left mouse button
	kRButton			=	2  ,	// Right mouse button
	kCancel				=	3  ,	// Control-break processing
	kMButton			=	4  ,	// Middle mouse button (three-button mouse)
	kXButton1			=	5  ,	// Windows 2000: X1 mouse button
	kXButton2			=	6  ,	// Windows 2000: X2 mouse button
	//—					=	7  ,	// Undefined
	kBack				=	8  ,	// BACKSPACE key
	kTab				=	9  ,	// TAB key
	//—					=	10 ,	// Reserved
	//—					=	11 ,	// Reserved
	kClear				=	12 ,	// CLEAR key
	kReturn				=	13 ,	// ENTER key
	//—					=	14 ,	// Undefined
	//—					=	15 ,	// Undefined
	kShift				=	16 ,	// SHIFT key
	kControl			=	17 ,	// CTRL key
	kMenu				=	18 ,	// ALT key
	kPause				=	19 ,	// PAUSE key
	kCapital			=	20 ,	// CAPS LOCK key
	kKana				=	21 ,	// IME Kana mode
	kHanguel			=	21 ,	// IME Hanguel mode (maintained for compatibility; use kHANGUL)
	kHangul				=	21 ,	// IME Hangul mode
	//—					=	22 ,	// Undefined
	kJunja				=	23 ,	// IME Junja mode
	kFinal				=	24 ,	// IME final mode
	kHanja				=	25 ,	// IME Hanja mode
	kKanji				=	25 ,	// IME Kanji mode
	//—					=	26 ,	// Undefined
	kEscape				=	27 ,	// ESC key
	kConvert			=	28 ,	// IME convert
	kNonConvert			=	29 ,	// IME nonconvert
	kAccept				=	30 ,	// IME accept
	kModeChange			=	31 ,	// IME mode change request
	kSpace				=	32 ,	// SPACEBAR
	kPrior				=	33 ,	// PAGE UP key
	kNext				=	34 ,	// PAGE DOWN key
	kEnd				=	35 ,	// END key
	kHome				=	36 ,	// HOME key
	kLeft				=	37 ,	// LEFT ARROW key
	kUp					=	38 ,	// UP ARROW key
	kRight				=	39 ,	// RIGHT ARROW key
	kDown				=	40 ,	// DOWN ARROW key
	kSelect				=	41 ,	// SELECT key
	kPrint				=	42 ,	// PRINT key
	kExecute			=	43 ,	// EXECUTE key
	kSnapshot			=	44 ,	// PRINT SCREEN key
	kInsert				=	45 ,	// INS key
	kDelete				=	46 ,	// DEL key
	kHelp				=	47 ,	// HELP key
	k0					=	48 ,	// 0 key
	k1					=	49 ,	// 1 key
	k2					=	50 ,	// 2 key
	k3					=	51 ,	// 3 key
	k4					=	52 ,	// 4 key
	k5					=	53 ,	// 5 key
	k6					=	54 ,	// 6 key
	k7					=	55 ,	// 7 key
	k8					=	56 ,	// 8 key
	k9					=	57 ,	// 9 key
	//—					=	58 ,	// Undefined
	//—					=	59 ,	// Undefined
	//—					=	60 ,	// Undefined
	//—					=	61 ,	// Undefined
	//—					=	62 ,	// Undefined
	//—					=	63 ,	// Undefined
	//—					=	64 ,	// Undefined
	kA					=	65 , 	// A key
	kB					=	66 , 	// B key
	kC					=	67 , 	// C key
	kD					=	68 , 	// D key
	kE					=	69 , 	// E key
	kF					=	70 , 	// F key
	kG					=	71 , 	// G key
	kH					=	72 , 	// H key
	kI					=	73 , 	// I key
	kJ					=	74 , 	// J key
	kK					=	75 , 	// K key
	kL					=	76 , 	// L key
	kM					=	77 , 	// M key
	kN					=	78 , 	// N key
	kO					=	79 , 	// O key
	kP					=	80 , 	// P key
	kQ					=	81 , 	// Q key
	kR					=	82 , 	// R key
	kS					=	83 , 	// S key
	kT					=	84 , 	// T key
	kU					=	85 , 	// U key
	kV					=	86 , 	// V key
	kW					=	87 , 	// W key
	kX					=	88 , 	// X key
	kY					=	89 , 	// Y key
	kZ					=	90 , 	// Z key
	kLWin				=	91 , 	// Left Windows key (Microsoft® Natural® keyboard)
	kRWin				=	92 , 	// Right Windows key (Natural keyboard)
	kApps				=	93 , 	// Applications key (Natural keyboard)
	//—					=	94 , 	// Reserved
	kSleep				=	95 , 	// Computer Sleep key
	kNumpad0			=	96 , 	// Numeric keypad 0 key
	kNumpad1			=	97 , 	// Numeric keypad 1 key
	kNumpad2			=	98 , 	// Numeric keypad 2 key
	kNumpad3			=	99 , 	// Numeric keypad 3 key
	kNumpad4			=	100,	// Numeric keypad 4 key
	kNumpad5			=	101,	// Numeric keypad 5 key
	kNumpad6			=	102,	// Numeric keypad 6 key
	kNumpad7			=	103,	// Numeric keypad 7 key
	kNumpad8			=	104,	// Numeric keypad 8 key
	kNumpad9			=	105,	// Numeric keypad 9 key
	kMultiply			=	106,	// Multiply key
	kAdd				=	107,	// Add key
	kSeparator			=	108,	// Separator key
	kSubtract			=	109,	// Subtract key
	kDecimal			=	110,	// Decimal key
	kDivide				=	111,	// Divide key
	kF1					=	112,	// F1 key
	kF2					=	113,	// F2 key
	kF3					=	114,	// F3 key
	kF4					=	115,	// F4 key
	kF5					=	116,	// F5 key
	kF6					=	117,	// F6 key
	kF7					=	118,	// F7 key
	kF8					=	119,	// F8 key
	kF9					=	120,	// F9 key
	kF10				=	121,	// F10 key
	kF11				=	122,	// F11 key
	kF12				=	123,	// F12 key
	kF13				=	124,	// F13 key
	kF14				=	125,	// F14 key
	kF15				=	126,	// F15 key
	kF16				=	127,	// F16 key
	kF17				=	128,	// F17 key
	kF18				=	129,	// F18 key
	kF19				=	130,	// F19 key
	kF20				=	131,	// F20 key
	kF21				=	132,	// F21 key
	kF22				=	133,	// F22 key
	kF23				=	134,	// F23 key
	kF24				=	135,	// F24 key
	//—					=	136,	// Unassigned
	//—					=	137,	// Unassigned
	//—					=	138,	// Unassigned
	//—					=	139,	// Unassigned
	//—					=	140,	// Unassigned
	//—					=	141,	// Unassigned
	//—					=	142,	// Unassigned
	//—					=	143,	// Unassigned
	kNumlock			=	144,	// NUM LOCK key
	kScroll				=	145,	// SCROLL LOCK key
	//					=	146,	// OEM specific
	//					=	147,	// OEM specific
	//					=	148,	// OEM specific
	//					=	149,	// OEM specific
	//					=	150,	// OEM specific
	//—					=	151,	// Unassigned
	//—					=	152,	// Unassigned
	//—					=	153,	// Unassigned
	//—					=	154,	// Unassigned
	//—					=	155,	// Unassigned
	//—					=	156,	// Unassigned
	//—					=	157,	// Unassigned
	//—					=	158,	// Unassigned
	//—					=	159,	// Unassigned
	kLShift				=	160,	// Left SHIFT key
	kRShift				=	161,	// Right SHIFT key
	kLControl			=	162,	// Left CONTROL key
	kRControl			=	163,	// Right CONTROL key
	kLMenu				=	164,	// Left MENU key
	kRMenu				=	165,	// Right MENU key
	kBrowserBack		=	166,	// Windows 2000: Browser Back key
	kBrowserForward		=	167,	// Windows 2000: Browser Forward key
	kBrowserRefresh		=	168,	// Windows 2000: Browser Refresh key
	kBrowserStop		=	169,	// Windows 2000: Browser Stop key
	kBrowserSearch		=	170,	// Windows 2000: Browser Search key
	kBrowserFavorites	=	171,	// Windows 2000: Browser Favorites key
	kBrowserHome		=	172,	// Windows 2000: Browser Start and Home key
	kVolumeMute			=	173,	// Windows 2000: Volume Mute key
	kVolumeDown			=	174,	// Windows 2000: Volume Down key
	kVolumeUp			=	175,	// Windows 2000: Volume Up key
	kMediaNextTrack		=	176,	// Windows 2000: Next Track key
	kMediaPrevTrack		=	177,	// Windows 2000: Previous Track key
	kMediaStop			=	178,	// Windows 2000: Stop Media key
	kMediaPlayPause		=	179,	// Windows 2000: Play/Pause Media key
	kLaunchMail			=	180,	// Windows 2000: Start Mail key
	kLaunchMediaSelect	=	181,	// Windows 2000: Select Media key
	kLaunchApp1			=	182,	// Windows 2000: Start Application 1 key
	kLaunchApp2			=	183,	// Windows 2000: Start Application 2 key
	//—					=	184,	// Reserved
	//—					=	185,	// Reserved
	kOEM1				=	186,	// Windows 2000: For the US standard keyboard, the ';:' key
	kOEMPlus			=	187,	// Windows 2000: For any country/region, the '+' key
	kOEMComma			=	188,	// Windows 2000: For any country/region, the ',' key
	kOEMMinus			=	189,	// Windows 2000: For any country/region, the '-' key
	kOEMPeriod			=	190,	// Windows 2000: For any country/region, the '.' key
	kOEM2				=	191,	// Windows 2000: For the US standard keyboard, the '/?' key
	kOEM3				=	192,	// Windows 2000: For the US standard keyboard, the '`~' key
	//—					=	193,	// Reserved
	//—					=	194,	// Reserved
	//—					=	195,	// Reserved
	//—					=	196,	// Reserved
	//—					=	197,	// Reserved
	//—					=	198,	// Reserved
	//—					=	199,	// Reserved
	//—					=	200,	// Reserved
	//—					=	201,	// Reserved
	//—					=	202,	// Reserved
	//—					=	203,	// Reserved
	//—					=	204,	// Reserved
	//—					=	205,	// Reserved
	//—					=	206,	// Reserved
	//—					=	207,	// Reserved
	//—					=	208,	// Reserved
	//—					=	209,	// Reserved
	//—					=	210,	// Reserved
	//—					=	211,	// Reserved
	//—					=	212,	// Reserved
	//—					=	213,	// Reserved
	//—					=	214,	// Reserved
	//—					=	215,	// Reserved
	//—					=	216,	// Unassigned
	//—					=	217,	// Unassigned
	//—					=	218,	// Unassigned
	kOEM4				=	219,	// Windows 2000: For the US standard keyboard, the '[{' key
	kOEM5				=	220,	// Windows 2000: For the US standard keyboard, the '\|' key
	kOEM6				=	221,	// Windows 2000: For the US standard keyboard, the ']}' key
	kOEM7				=	222,	// Windows 2000: For the US standard keyboard, the 'single-quote/double-quote' key
	kOEM8				=	223,	// 
	//—					=	224,	// Reserved
	//					=	225,	// OEM specific
	kOEM102				=	226,	// Windows 2000: Either the angle bracket key or the backslash key on the RT 102-key keyboard
	//					=	227,	// OEM specific
	//					=	228,	// OEM specific
	kProcessKey			=	229,	// Windows 95/98, Windows NT 4.0, Windows 2000: IME PROCESS key
	//					=	230,	// OEM specific
	kPacket				=	231,	// Windows 2000: Used to pass Unicode characters as if they were keystrokes. The kPACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP
	//—					=	232,	// Unassigned
	//					=	233,	// OEM specific
	//					=	234,	// OEM specific
	//					=	235,	// OEM specific
	//					=	236,	// OEM specific
	//					=	237,	// OEM specific
	//					=	238,	// OEM specific
	//					=	239,	// OEM specific
	//					=	240,	// OEM specific
	//					=	241,	// OEM specific
	//					=	242,	// OEM specific
	//					=	243,	// OEM specific
	//					=	244,	// OEM specific
	//					=	245,	// OEM specific
	kAttn				=	246,	// Attn key
	kCrSel				=	247,	// CrSel key
	kExSel				=	248,	// ExSel key
	kErEOF				=	249,	// Erase EOF key
	kPlay				=	250,	// Play key
	kZoom				=	251,	// Zoom key
	kNoName				=	252,	// Reserved for future use
	kPA1				=	253,	// PA1 key
	kOEMClear			=	254,	// Clear key
};


enum class BvMouseButton : u8
{
	kNone = 0,
	kLeft = BvBit(0),
	kRight = BvBit(1),
	kMiddle = BvBit(2),
	kButton4 = BvBit(3),
	kButton5 = BvBit(4),
	kWheel = BvBit(5),
	kHWheel = BvBit(6)
};
BV_USE_ENUM_CLASS_OPERATORS(BvMouseButton);


const char* const GetKeyName(BvKey key);